### ISSUE TITLE
/bin/sh: syno_clear_drive_error.sh: command not found

### ISSUE THREAD

**Issue by Donnit86** [007revad/Synology_clear_drive_error#15]
Hello everyone,

After reporting an error I am having with one of the disk on Reddit, I was recommended to try the syno script.

All goes well until I try to run and meet an error.
I tried again after install Z shell, but still the same error.

Any idea what I can do?

Thanks

**Comment by 007revad** [comment]
If you've cd'd to the folder containing the script you need run the script you need to run the script with 
`sudo ./syno_clear_drive_error.sh`

If the path to the script contains spaces you need to enclose the path/file in double quotes 
`sudo "/volume1/your folder/syno_clear_drive_error.sh"`

If the script is located in your home folder you need to make it executable like.
`sudo chmod +x /volume1/homes/donnit/scripts/syno_clear_drive_error.sh`

**Comment by Donnit86** [comment]
Thanks Revad,

I put the Synology folder into Homes.

It worked with "sudo ./syno_clear_drive_error.sh"
Or kinda

It says

> sh-4.4# sudo ./syno_clear_drive_error.sh
> Synology_Clear_Drive_Error v1.0.3
> 
> 0 status_critical entries found

Yet if I go to "Storage manager" the first thing I see is big red logo with "Critical" written next to it.
"Issues have occurred to Storage Pool 1. Please go to Storage page..."

I attach screenshots for more details

https://i.ibb.co/Dg0xCwC/photo-2024-05-29-11-27-39.jpg

https://i.ibb.co/zXT4S4L/photo-2024-05-29-11-27-40.jpg

**Comment by 007revad** [comment]
I had the same "0 status_critical entries found" when I had recently had a drive's status change to critical due to dust in the SATA connector. I didn't have time to work out where DSM was hiding the critical status so I did these steps instead:

1. Open Storage Manager and select the drive.
2. Click on Actions then select Deactivate.
3. Shut down the NAS.
4. Remove the drive from the NAS.
5. Boot the NAS.
6. Shut down the NAS.
7. Insert the drive.
8. Boot the NAS.
9. Open Storage Manager and click on Repair.
10. Select the drive, click Next then Repair.

**Comment by Donnit86** [comment]
From the "Action" button I can only deactivate drive1 which is the one that works. When I select disk 2 the option to deactivate is not there.

For more info, the first time I encountered the error, DSM recommended me to deactivate the disk, which I did. Rebooted and reactivated it. Before I do that health statut was "Critical" which it is not now.
Also as recommended on Reddit, I plugged disk2 on a computer and erase all partitions.

**Comment by 007revad** [comment]
Can you show me a screenshot of  Storage Manager > HDD/SSD

**Comment by Donnit86** [comment]
Absolutely


https://i.ibb.co/rKPqVvF/photo-2024-05-30-13-21-48.jpg

[](https://i.ibb.co/rKPqVvF/photo-2024-05-30-13-21-48.jpg
)

**Comment by 007revad** [comment]
Both HDDs are showing as healthy. But only HDD 1 is assigned to storage pool 1. If you go to to storage pool 1 and click on the "repair now" link in this image https://i.ibb.co/zXT4S4L/photo-2024-05-29-11-27-40.jpg it should repair the storage pool, and volume.

**Comment by Donnit86** [comment]
I did that several times with no success

Here are a few screenshots of the procedure: 

https://postimg.cc/gallery/QhhxK9f
